//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_tileset_H
#define METASPRITE_sprite_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_tileset_TILE_ORIGIN 0
#define sprite_tileset_TILE_H 8
#define sprite_tileset_WIDTH 16
#define sprite_tileset_HEIGHT 16
#define sprite_tileset_TILE_COUNT 61
#define sprite_tileset_PIVOT_X 8
#define sprite_tileset_PIVOT_Y 8
#define sprite_tileset_PIVOT_W 16
#define sprite_tileset_PIVOT_H 16

BANKREF_EXTERN(sprite_tileset)

extern const palette_color_t sprite_tileset_palettes[4];
extern const uint8_t sprite_tileset_tiles[976];

extern const metasprite_t* const sprite_tileset_metasprites[32];

#endif