/*
    TILESET1_MAP.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_TILESET1_MAP_H__
#define __MAP_TILESET1_MAP_H__

#define TILESET1_MAP_WIDTH 32
#define TILESET1_MAP_HEIGHT 4

extern const void __bank_TILESET1_MAP_DATA;

extern const unsigned char TILESET1_MAP_DATA[];

#endif
