/*
    TILESET1_TILES.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_TILESET1_TILES_H__
#define __MAP_TILESET1_TILES_H__

#define TILESET1_TILE_COUNT 67

#define TILESET1_PALETTE 0x1B

extern const void __bank_TILESET1_TILE_DATA;

extern const unsigned char TILESET1_TILE_DATA[];

#endif
